-- Searchable metadata schema (H2 / PostgreSQL-compatible standard SQL).

CREATE TABLE IF NOT EXISTS NAMESPACE (
    ID            VARCHAR(64) PRIMARY KEY,
    NAME          VARCHAR(256) NOT NULL,
    CONFIG_JSON   CLOB NOT NULL,
    CREATED_AT    TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_AT    TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS INDEX_METADATA (
    NAMESPACE_ID     VARCHAR(64) PRIMARY KEY,
    DOCUMENT_COUNT   BIGINT NOT NULL DEFAULT 0,
    INDEX_SIZE_BYTES BIGINT NOT NULL DEFAULT 0,
    STATUS           VARCHAR(32) NOT NULL,
    LAST_UPDATED     TIMESTAMP WITH TIME ZONE NOT NULL,
    STATISTICS_JSON  CLOB,
    CONSTRAINT FK_INDEX_METADATA_NAMESPACE
        FOREIGN KEY (NAMESPACE_ID) REFERENCES NAMESPACE (ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS DOCUMENT_SOURCE (
    NAMESPACE_ID     VARCHAR(64)  NOT NULL,
    DOCUMENT_ID      VARCHAR(128) NOT NULL,
    SOURCE_TYPE      VARCHAR(64)  NOT NULL,
    SOURCE_LOCATION  VARCHAR(2048) NOT NULL,
    CONTENT_HASH     VARCHAR(128),
    SOURCE_UPDATED   TIMESTAMP WITH TIME ZONE,
    INDEXED_AT       TIMESTAMP WITH TIME ZONE NOT NULL,
    PRIMARY KEY (NAMESPACE_ID, DOCUMENT_ID),
    CONSTRAINT FK_DOCUMENT_SOURCE_NAMESPACE
        FOREIGN KEY (NAMESPACE_ID) REFERENCES NAMESPACE (ID) ON DELETE CASCADE
);
