spring.application.name=searchable-api

server.port=8080
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

searchable.data-directory=./data
searchable.persistence.type=H2
searchable.persistence.url=jdbc:h2:./data/metadata;MODE=PostgreSQL
searchable.persistence.username=sa
searchable.persistence.password=
searchable.index.directory=./data/indexes
searchable.global.default-architecture=FULL_TEXT
searchable.global.default-search-strategy=SEQUENTIAL
